-- 1. 建立客戶表 (Customers)
-- 雖然你的 Prompt 沒直接寫入這張表，但 order 需要 customer_id，所以必須要有這張表
CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_user_id TEXT UNIQUE NOT NULL, -- 用來存 LINE 的 User ID
    display_name TEXT,                 -- 用來存 LINE 的顯示名稱
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. 建立產品庫存表 (Products)
-- 對應你的 CheckStockAgent 和 menu 資訊
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name TEXT UNIQUE NOT NULL, -- 商品名稱 (設定唯一，方便 Agent 查詢)
    price INTEGER NOT NULL,            -- 價格
    quantity INTEGER NOT NULL DEFAULT 0, -- 庫存數量
    description TEXT,                  -- 商品描述 (可選，給 ChatAgent 用)
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. 建立訂單表 ("order")
-- 注意：因為 order 是 SQL 保留字，必須用雙引號 "order" 包起來
-- 這完全對應你的 insert_order_prompt: VALUES ('{{order_info_json}}'::jsonb, 1)
CREATE TABLE "order" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES customers(id), -- 關聯到 customers 表
    order_info JSONB NOT NULL,                   -- 關鍵：儲存 JSON 格式的訂單內容
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. 插入一些測試用的假資料 (Seed Data)
-- 這樣你的 Agent 才有東西可以查詢和測試

-- 建立一個預設的測試用戶 (id = 1)，對應 Prompt 中的 "VALUES (..., 1)"
INSERT INTO customers (line_user_id, display_name)
VALUES ('U1234567890abcdef', 'Test User');

-- 建立菜單與庫存 (呼應你的 Prompt 範例：蘋果、橘子等)
INSERT INTO products (product_name, price, quantity, description)
VALUES
    ('apple', 30, 10, '新鮮富士蘋果'),
    ('orange', 25, 20, '多汁香甜柳橙'),
    ('guava', 20, 0, '脆甜芭樂 (目前缺貨測試用)'),
    ('peach', 150, 5, '拉拉山水蜜桃');

-- 建立一筆歷史訂單測試 JSONB 功能
INSERT INTO "order" (customer_id, order_info)
VALUES
    (1, '{"product_name": ["apple", "orange"], "order_quantity": [2, 1]}'::jsonb);